# Generated by Django 5.2.17 on 2026-09-07 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chores", "0001_initial"),
        ("households", "0002_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="chore",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chore",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_chores",
                to="households.partner",
            ),
        ),
    ]
