# Generated by Django 5.2.17 on 2026-09-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chores", "0002_chore_completed_at_chore_completed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="chore",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
