# Generated by Django 5.2.17 on 2026-09-07 17:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chores", "0003_chore_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("fixed_daily", "Daily"),
                            ("fixed_weekly", "Weekly"),
                            ("fixed_monthly_date", "Monthly (specific date)"),
                            ("fixed_monthly_relative", "Monthly (relative day)"),
                            ("interval_after_completion", "Interval after completion"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "month_day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "month_ordinal",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "First"),
                            (2, "Second"),
                            (3, "Third"),
                            (4, "Fourth"),
                            (-1, "Last"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "month_weekday",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                ("interval_days", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "chore",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrence",
                        to="chores.chore",
                    ),
                ),
            ],
        ),
    ]
